name: Sync to 4iProto--abdal-4iproto-cli

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Push to 4iProto--abdal-4iproto-cli
        run: |
          git remote add target https://x-access-token:${{ secrets.SYNC_TOKEN_REPO }}@github.com/4iProto/abdal-4iproto-cli.git
          git push target --force --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/*